name: "FlakeHub Build & Publish"

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  publish-flake:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install Nix
        uses: DeterminateSystems/determinate-nix-action@v3

      - name: Publish to FlakeHub
        uses: DeterminateSystems/flakehub-push@main
        with:
          name: fortydeux/Fortydeux-NixOS-System-Flake
          rolling: true
          visibility: public
          include-output-paths: true

  build-systems:
    runs-on: ubuntu-latest
    needs: publish-flake
    strategy:
      matrix:
        system: [archerfish-nixos, killifish-nixos, pufferfish-nixos, blackfin-nixos, blacktetra-nixos]
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install Nix
        uses: DeterminateSystems/determinate-nix-action@v3

      - name: Build NixOS System
        run: |
          # Enable ms-surface module for Surface devices
          if [[ "${{ matrix.system }}" == "archerfish-nixos" || "${{ matrix.system }}" == "killifish-nixos" ]]; then
            echo "Building Surface device with ms-surface module..."
            # Uncomment ms-surface module for killifish if needed
            if [[ "${{ matrix.system }}" == "killifish-nixos" ]]; then
              sed -i 's|#.*../../system-modules/ms-surface.nix|../../system-modules/ms-surface.nix|' nixos-config/hosts/killifish/configuration.nix
            fi
          fi
          
          # Build system components (excluding kernel to avoid space issues)
          echo "Building system configuration components..."
          nix build --no-link --print-build-logs ".#nixosConfigurations.${{ matrix.system }}.config.system.build.etc" || echo "etc build failed but continuing..."
          
          echo "Building system packages..."
          nix build --no-link --print-build-logs ".#nixosConfigurations.${{ matrix.system }}.config.environment.systemPackages" || echo "systemPackages build failed but continuing..."
          
          echo "Building systemd units..."
          nix build --no-link --print-build-logs ".#nixosConfigurations.${{ matrix.system }}.config.system.build.units" || echo "units build failed but continuing..."
          
          echo "Building initial ramdisk..."
          nix build --no-link --print-build-logs ".#nixosConfigurations.${{ matrix.system }}.config.system.build.initialRamdisk" || echo "initrd build failed but continuing..."
          
          echo "Building activation script..."
          nix build --no-link --print-build-logs ".#nixosConfigurations.${{ matrix.system }}.config.system.build.activationScript" || echo "activation build failed but continuing..."
          
          echo "Skipping kernel build due to GitHub runner disk space constraints (~14GB)"
          echo "Kernel builds require ~30GB+ and are the main cause of local build slowness"

      - name: Report build status
        if: always()
        run: |
          echo "Build completed for ${{ matrix.system }}"
          echo "Built derivations should now be available in binary cache"
