name: "Build Systems"

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-systems:
    runs-on: ubuntu-latest-m
    strategy:
      matrix:
        system: [archerfish-nixos, killifish-nixos, pufferfish-nixos, blackfin-nixos, blacktetra-nixos]
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install Nix
        uses: DeterminateSystems/determinate-nix-action@v3

      - name: Build NixOS System
        run: |
          echo "Building complete NixOS system (including Surface kernels)..."
          nix build --no-link --print-build-logs ".#nixosConfigurations.${{ matrix.system }}.config.system.build.toplevel"

      - name: Report build status
        if: always()
        run: |
          echo "Build completed for ${{ matrix.system }}"
          echo "Complete system build (including Surface kernels) cached"
